name: Lezou's Blog
email: lezou.dali@gmail.com
description: Journey to becoming a professional problem solver... oh and awesome developer.

baseurl: ""
url: http://lezoudali.com
twitter_username: lezoudali
github_username: lezoudali

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

# Build settings
markdown: kramdown

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']