# Site settings
title: Code Noir | Lezou Dali
description: "Journey to becoming a professional problem solver..."
url: "lezoudali.github.io"
author:
  name: "Lezou Dali"
  url: "lezoudali.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"



